version: '3'
services:
  web:
    build: .
    image: goodwill_currency:latest
    ports:
      - "3001:3000"
    dns: "8.8.8.8"
    volumes:
      - ".:/app"
    env_file: .env
    links:
      - redis:redis
    external_links:
      - postgres:db
    command: bash -c "bin/rake assets:precompile && bin/rake db:create && bin/rake db:migrate && bin/rails s"
    networks:
      - production
  redis:
    image: redis:latest

networks:
  production:
    external: true
# Refer to: https://viky.co.in/2017/12/18/link-external-containers-using-docker-compose/
# Useful commands:
# docker network create production
# docker network connect production postgres
